import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";

import Providers from "./providers";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";

const workSans = Work_Sans({
  subsets: ["latin-ext"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-work-sans",
});

export const metadata: Metadata = {
  title: "Dragon Ball Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.variable} dark:bg-slate-800 bg-gray-300`}>
        <Providers>
          <Header />
          <PageTransition>{children}</PageTransition>
        </Providers>
      </body>
    </html>
  );
}
